- name: laod maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven


- name: Install MYSQL client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.kommanuthala.store -uroot -pRoboshop@1 < /app/db/schema.sql

- name: Load user creation
  ansible.builtin.shell: mysql -h mysql mysql-dev.kommanuthala.store -uroot -pRoboshop@1 < /app/db/user.sql

- name: load master data
  ansible.builtin.shell: mysql -h mysql mysql-dev.kommanuthala.store -uroot -pRoboshop@1 < /app/db/master-data.sql