    - name: Disable default nginx
      ansible.builtin.shell: dnf module disable nginx -y
 
    - name: Enable nginx 24
      ansible.builtin.shell: dnf module enable nginx:1.24 -y 

    - name: Install nginx
      ansible.builtin.dnf: 
        name: nginx
        state: present
  
    - name: copy nginx congfig file 
      ansible.builtin.copy: 
        src: nginx.conf
        dest: /etc/nginx/nginx.config

    - name: Remove old folder
      ansible.builtin.file:
       path: /etc/share/nginx/html
       state: absent
  
    - name: create app folder content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory 

    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: start nginx
      ansible.builtin.systemd_service: 
        state: restarted
        name: nginx