- name: disabled node js and enable node js 20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Instll nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: include artifact downaload
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name: install node js depenencies
  ansible.builtin.shell: npm install

- name: install systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml

